import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{supabase}from"./supabase";import"./style.css";
const menu=[["dash","⌂","Dashboard"],["orders","▣","Pedidos"],["prod","⚙","Produção"],["printers","🖨","Impressoras"],["products","◈","Produtos"],["customers","♙","Clientes"],["ship","□","Despachos"]];
const sl={waiting:"Aguardando",production:"Em produção",ready:"Pronto",shipped:"Despachado",cancelled:"Cancelado"};
const pl={available:"Disponível",printing:"Imprimindo",maintenance:"Manutenção",problem:"Problema"};
function App(){const[s,setS]=useState(null),[v,setV]=useState("dash"),[d,setD]=useState({orders:[],products:[],printers:[],customers:[],runs:[],shipments:[]});
useEffect(()=>{supabase.auth.getSession().then(x=>setS(x.data.session));const x=supabase.auth.onAuthStateChange((_e,z)=>setS(z));return()=>x.data.subscription.unsubscribe()},[]);
useEffect(()=>{if(s)load()},[s]);async function load(){const[q,p,pr,c,r,sh]=await Promise.all([supabase.from("orders").select("*,customers(name),order_items(id,quantity,products(name))").order("created_at",{ascending:false}),supabase.from("products").select("*").eq("active",true).order("name"),supabase.from("printers").select("*").order("id"),supabase.from("customers").select("*").order("name"),supabase.from("production_runs").select("*,order_items(order_id,products(name)),printers(name)").order("created_at",{ascending:false}),supabase.from("shipments").select("*,orders(order_number,customers(name))").order("shipped_at",{ascending:false})]);setD({orders:q.data||[],products:p.data||[],printers:pr.data||[],customers:c.data||[],runs:r.data||[],shipments:sh.data||[]})}
if(!s)return <Login/>;return <div className="app"><aside><div className="brand"><b>SV</b><div><strong>STUDIOVIBES</strong><small>ERP • Produção 3D</small></div></div><nav>{menu.map(x=><button className={v===x[0]?"on":""} onClick={()=>setV(x[0])} key={x[0]}><i>{x[1]}</i>{x[2]}</button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}>Sair</button></aside><main><header><div><small>STUDIOVIBES / {menu.find(x=>x[0]===v)[2]}</small><h1>{menu.find(x=>x[0]===v)[2]}</h1></div><button onClick={load}>↻ Atualizar</button></header><Page v={v} d={d} load={load}/></main></div>}
function Login(){const[e,setE]=useState(""),[p,setP]=useState(""),[m,setM]=useState("");async function go(x){x.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:e,password:p});if(error)setM(error.message)}return <div className="login"><form onSubmit={go}><div className="big">SV</div><h1>STUDIOVIBES</h1><p>ERP de produção 3D</p><input type="email" placeholder="E-mail" value={e} onChange={x=>setE(x.target.value)} required/><input type="password" placeholder="Senha" value={p} onChange={x=>setP(x.target.value)} required/><button className="primary">Entrar</button>{m&&<small className="err">{m}</small>}</form></div>}
function Page({v,d,load}){if(v==="dash")return <Dash d={d}/>;if(v==="orders")return <Orders d={d} load={load}/>;if(v==="prod")return <Prod d={d} load={load}/>;if(v==="printers")return <Printers d={d} load={load}/>;if(v==="products")return <Products d={d} load={load}/>;if(v==="customers")return <Customers d={d} load={load}/>;return <Ship d={d} load={load}/>}
const Pill=({s})=><span className={"pill "+s}>{sl[s]||pl[s]||s}</span>;
function Dash({d}){let a=d.orders.filter(x=>!["shipped","cancelled"].includes(x.status)).length,b=d.orders.filter(x=>x.status==="production").length,c=d.orders.filter(x=>x.status==="ready").length,e=d.orders.filter(x=>x.status==="shipped").length;return <><p className="muted">Visão geral da operação.</p><div className="cards"><Card t="Pedidos em aberto" n={a}/><Card t="Em produção" n={b}/><Card t="Prontos" n={c}/><Card t="Despachados" n={e}/></div><div className="cols"><section className="panel"><h2>Impressoras</h2>{d.printers.map(p=><div className="row" key={p.id}><b>🖨 {p.name}</b><Pill s={p.status}/></div>)}</section><section className="panel"><h2>Pedidos recentes</h2>{d.orders.slice(0,6).map(o=><div className="row" key={o.id}><b>#{o.order_number}</b><Pill s={o.status}/></div>)}{!d.orders.length&&<Empty/>}</section></div></>}
function Card({t,n}){return <div className="card"><small>{t}</small><strong>{n}</strong></div>}function Empty(){return <div className="empty">Nenhum registro.</div>}
function Orders({d,load}){const[f,setF]=useState({num:"",client:"",product:"",qty:1,due:""});async function add(e){e.preventDefault();let c=d.customers.find(x=>x.name.toLowerCase()===f.client.toLowerCase());if(!c){let z=await supabase.from("customers").insert({name:f.client}).select().single();if(z.error)return alert(z.error.message);c=z.data}let o=await supabase.from("orders").insert({order_number:f.num||String(Date.now()).slice(-6),customer_id:c.id,due_date:f.due||null}).select().single();if(o.error)return alert(o.error.message);await supabase.from("order_items").insert({order_id:o.data.id,product_id:+f.product,quantity:+f.qty});setF({num:"",client:"",product:"",qty:1,due:""});load()}return <><form className="form" onSubmit={add}><input placeholder="Nº pedido" value={f.num} onChange={x=>setF({...f,num:x.target.value})}/><input placeholder="Cliente" value={f.client} onChange={x=>setF({...f,client:x.target.value})} required/><select value={f.product} onChange={x=>setF({...f,product:x.target.value})} required><option value="">Produto</option>{d.products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input type="number" min="1" value={f.qty} onChange={x=>setF({...f,qty:x.target.value})}/><input type="date" value={f.due} onChange={x=>setF({...f,due:x.target.value})}/><button className="primary">+ Novo pedido</button></form><Table rows={d.orders.map(o=>{let i=o.order_items?.[0];return [<b>#{o.order_number}</b>,o.customers?.name||"—",i?.products?.name||"—",i?.quantity||"—",o.due_date||"—",<Pill s={o.status}/>]})} heads={["Pedido","Cliente","Produto","Qtd","Prazo","Status"]}/></>}
function Prod({d,load}){const[form,setF]=useState({item:"",printer:"",qty:1});let items=d.orders.filter(o=>o.status==="waiting").flatMap(o=>(o.order_items||[]).map(i=>({id:i.id,order:o.id,label:`#${o.order_number} — ${i.products?.name}`})));async function go(e){e.preventDefault();let z=items.find(x=>x.id===+form.item);await supabase.from("production_runs").insert({order_item_id:+form.item,printer_id:+form.printer,quantity:+form.qty,status:"printing",started_at:new Date().toISOString()});await supabase.from("orders").update({status:"production"}).eq("id",z.order);await supabase.from("printers").update({status:"printing"}).eq("id",+form.printer);load()}async function done(r){await supabase.from("production_runs").update({status:"completed",produced_quantity:r.quantity,finished_at:new Date().toISOString()}).eq("id",r.id);await supabase.from("orders").update({status:"ready"}).eq("id",r.order_items.order_id);await supabase.from("printers").update({status:"available"}).eq("id",r.printer_id);load()}return <><form className="form" onSubmit={go}><select value={form.item} onChange={e=>setF({...form,item:e.target.value})} required><option value="">Pedido</option>{items.map(i=><option value={i.id} key={i.id}>{i.label}</option>)}</select><select value={form.printer} onChange={e=>setF({...form,printer:e.target.value})} required><option value="">Impressora</option>{d.printers.filter(x=>x.status==="available").map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input type="number" min="1" value={form.qty} onChange={e=>setF({...form,qty:e.target.value})}/><button className="primary">Iniciar impressão</button></form><Table rows={d.runs.map(r=>[`#${r.order_items?.order_id||"—"}`,r.order_items?.products?.name||"—",r.printers?.name||"—",r.quantity,r.status==="printing"?<button onClick={()=>done(r)}>Concluir</button>:<Pill s="ready"/>])} heads={["Pedido","Produto","Impressora","Qtd","Ação"]}/></>}
function Printers({d,load}){async function ch(id,s){await supabase.from("printers").update({status:s}).eq("id",id);load()}return <div className="cards3">{d.printers.map(p=><section className="panel" key={p.id}><h2>🖨 {p.name}</h2><p>{p.model||"Modelo não informado"}</p><Pill s={p.status}/><select value={p.status} onChange={e=>ch(p.id,e.target.value)}><option value="available">Disponível</option><option value="printing">Imprimindo</option><option value="maintenance">Manutenção</option><option value="problem">Problema</option></select></section>)}</div>}
function Products({d,load}){const[n,setN]=useState("");async function add(e){e.preventDefault();await supabase.from("products").insert({name:n});setN("");load()}return <><form className="quick" onSubmit={add}><input placeholder="Nome do novo produto" value={n} onChange={e=>setN(e.target.value)} required/><button className="primary">Adicionar</button></form><Table rows={d.products.map(p=>[p.code||"—",<b>{p.name}</b>,p.size_cm?p.size_cm+" cm":"—",p.weight_g?p.weight_g+" g":"—",p.estimated_hours?p.estimated_hours+" h":"—"])} heads={["Código","Produto","Tamanho","Peso","Tempo"]}/></>}
function Customers({d,load}){const[n,setN]=useState("");async function add(e){e.preventDefault();await supabase.from("customers").insert({name:n});setN("");load()}return <><form className="quick" onSubmit={add}><input placeholder="Nome do cliente" value={n} onChange={e=>setN(e.target.value)} required/><button className="primary">Adicionar</button></form><Table rows={d.customers.map(c=>[<b>{c.name}</b>,c.phone||"—",c.email||"—"])} heads={["Cliente","Telefone","E-mail"]}/></>}
function Ship({d,load}){let ready=d.orders.filter(x=>x.status==="ready");async function go(o){await supabase.from("shipments").insert({order_id:o.id});await supabase.from("orders").update({status:"shipped"}).eq("id",o.id);load()}return <><section className="panel"><h2>Prontos para despacho</h2>{ready.map(o=><div className="row" key={o.id}><b>#{o.order_number} — {o.customers?.name}</b><button className="primary" onClick={()=>go(o)}>Despachar</button></div>)}{!ready.length&&<Empty/>}</section><Table rows={d.shipments.map(s=>[`#${s.orders?.order_number}`,s.orders?.customers?.name||"—",new Date(s.shipped_at).toLocaleDateString("pt-BR"),s.tracking_code||"—"])} heads={["Pedido","Cliente","Data","Rastreio"]}/></>}
function Table({heads,rows}){return <section className="panel table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</section>}
createRoot(document.getElementById("root")).render(<App/>);
